apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlwala
  labels:
    app: mylabel

spec:
  replicas: 3
  selector:
    matchLabels:
      app: mylabel

  template:
    metadata:
      labels:
        app: mylabel

    spec:
      containers:
        - name: mycontainer
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef:
                    name: mysecret
                    key: MYSQL_ROOT_PASSWORD
